---
- name: Configure goingmerry Raspberry Pi 5 home server
  hosts: goingmerry
  vars_files:
    - vars/main.yml
    - vars/vault.yml

  pre_tasks:
    - name: Install required Ansible collections and roles
      command: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml
      changed_when: false

  roles:
    - { role: system, tags: system }
    - { role: users, tags: users }
    - { role: dotfiles, tags: dotfiles }
    - { role: docker, tags: docker }
    - { role: storage, tags: storage }
    - { role: nordvpn, tags: nordvpn}
#    - { role: monitoring, tags: monitoring }
    - { role: media, tags: media }
    - { role: caddy, tags: caddy }
