---
- name: Create caddy compose directory
  file:
    path: "{{ caddy_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create caddy config directory
  file:
    path: "{{ caddy_compose_dir }}/config"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create caddy data directory
  file:
    path: "{{ caddy_compose_dir }}/data"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy_compose_dir }}/config/Caddyfile"
    owner: root
    group: root
    mode: "0644"
  notify: restart caddy

- name: Deploy caddy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ caddy_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  notify: restart caddy

- name: Start caddy
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_compose_dir }}"
    state: present
